name: asu_traffic_api
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: ivan koop <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  convert: ^2.0.1
  logging: '>=0.9.0<2.0.0'
  sqljocky: ^0.14.1

dev_dependencies:
  test: ^0.12.0
